name: auto-ml 

dependencies:
  - python>=3.6
  - ipywidgets==7.4.0
  - matplotlib==3.0.0
  - numpy==1.15.2
  - pandas==0.23.4
  - scikit-learn==0.20.0
  - seaborn==0.9.0
  - swig
  - pip:
    - auto-sklearn==0.5.0
